"""Add location tracking to reports

Revision ID: 6d3f53d519cd
Revises: 0001
Create Date: 2026-04-07 18:33:51.724525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '6d3f53d519cd'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field_reports', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('field_reports', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('field_reports', sa.Column('coordinator_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('field_reports', 'coordinator_name')
    op.drop_column('field_reports', 'longitude')
    op.drop_column('field_reports', 'latitude')
    # ### end Alembic commands ###
